# Generated by Django 4.1.7 on 2023-02-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_email_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'история', 'verbose_name_plural': 'история'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='history',
        ),
    ]
