# Generated by Django 4.1.7 on 2023-02-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ/история', 'verbose_name_plural': 'заказы/истории'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='order/history',
        ),
    ]
