# Generated by Django 4.1.7 on 2023-02-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
